artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://storage.googleapis.com/mledu-datasets/cats_and_dogs_filtered.zip #change
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/extracted



prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5



training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5
  training_data: artifacts/data_ingestion/cats_and_dogs_filtered #change

mlflow:
  mlflow_uri: http://ec2-18-184-143-36.eu-central-1.compute.amazonaws.com:5000/ #change

